-- V13: Convert monetary and stock columns back to DECIMAL(19,4) for exact precision
-- Correcting V9 (revert to double) after Java JPA entities were refactored to use BigDecimal

-- PRODUCTS
ALTER TABLE products MODIFY COLUMN price_cost DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE products MODIFY COLUMN price_sale DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE products MODIFY COLUMN price_sale_bulk DECIMAL(19,4) DEFAULT 0.0000;

-- CUSTOMERS
ALTER TABLE customers MODIFY COLUMN credit_limit DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE customers MODIFY COLUMN balance DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE customers MODIFY COLUMN default_discount DECIMAL(19,4) DEFAULT 0.0000;

-- EXPENSES
ALTER TABLE expenses MODIFY COLUMN amount DECIMAL(19,4) DEFAULT 0.0000;

-- PAYMENTS
ALTER TABLE payments MODIFY COLUMN amount DECIMAL(19,4) DEFAULT 0.0000;

-- SALES
ALTER TABLE sales MODIFY COLUMN subtotal DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE sales MODIFY COLUMN total_discount DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE sales MODIFY COLUMN total_tax DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE sales MODIFY COLUMN total_ice DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE sales MODIFY COLUMN total DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE sales MODIFY COLUMN exchange_rate DECIMAL(19,4) DEFAULT 1.0000;
ALTER TABLE sales MODIFY COLUMN withholding_tax_rate DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE sales MODIFY COLUMN withholding_tax DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE sales MODIFY COLUMN paid_amount DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE sales MODIFY COLUMN change_amount DECIMAL(19,4) DEFAULT 0.0000;

-- SALE ITEMS
ALTER TABLE sale_items MODIFY COLUMN unit_price DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE sale_items MODIFY COLUMN discount DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE sale_items MODIFY COLUMN line_base DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE sale_items MODIFY COLUMN line_discount DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE sale_items MODIFY COLUMN line_ice DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE sale_items MODIFY COLUMN line_tax DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE sale_items MODIFY COLUMN line_total DECIMAL(19,4) DEFAULT 0.0000;

-- PURCHASES
ALTER TABLE purchases MODIFY COLUMN subtotal DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE purchases MODIFY COLUMN total_tax DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE purchases MODIFY COLUMN total DECIMAL(19,4) DEFAULT 0.0000;

-- PURCHASE ITEMS
ALTER TABLE purchase_items MODIFY COLUMN cost_price DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE purchase_items MODIFY COLUMN subtotal DECIMAL(19,4) DEFAULT 0.0000;

-- STOCK MOVEMENTS
ALTER TABLE stock_movements MODIFY COLUMN unit_cost_price DECIMAL(19,4) DEFAULT 0.0000;
ALTER TABLE stock_movements MODIFY COLUMN unit_sale_price DECIMAL(19,4) DEFAULT 0.0000;
