-- V17: Convert DOUBLE columns used for money/quantities to DECIMAL(19,4)
-- Backup recommended before applying in production.

ALTER TABLE customers MODIFY COLUMN balance DECIMAL(19,4) DEFAULT 0;
ALTER TABLE customers MODIFY COLUMN credit_limit DECIMAL(19,4) DEFAULT 0;
ALTER TABLE customers MODIFY COLUMN default_discount DECIMAL(19,4) DEFAULT 0;

ALTER TABLE products MODIFY COLUMN price_cost DECIMAL(19,4);
ALTER TABLE products MODIFY COLUMN price_sale DECIMAL(19,4);
ALTER TABLE products MODIFY COLUMN price_sale_bulk DECIMAL(19,4);
ALTER TABLE products MODIFY COLUMN profit_margin DECIMAL(19,4);
ALTER TABLE products MODIFY COLUMN tax_rate DECIMAL(9,4);
ALTER TABLE products MODIFY COLUMN ice_rate DECIMAL(9,4);
ALTER TABLE products MODIFY COLUMN bulk_quantity DECIMAL(19,4);
ALTER TABLE products MODIFY COLUMN conversion_factor DECIMAL(19,8);

ALTER TABLE product_barcodes MODIFY COLUMN quantity DECIMAL(19,4) DEFAULT 1;

ALTER TABLE stock_branch MODIFY COLUMN stock_current DECIMAL(19,4) DEFAULT 0;
ALTER TABLE stock_branch MODIFY COLUMN stock_min DECIMAL(19,4) DEFAULT 0;
ALTER TABLE stock_branch MODIFY COLUMN stock_max DECIMAL(19,4) DEFAULT 0;

ALTER TABLE stock_movements MODIFY COLUMN qty DECIMAL(19,4) DEFAULT 0;
ALTER TABLE stock_movements MODIFY COLUMN stock_before DECIMAL(19,4);
ALTER TABLE stock_movements MODIFY COLUMN stock_after DECIMAL(19,4);

ALTER TABLE purchases MODIFY COLUMN subtotal DECIMAL(19,4) DEFAULT 0;
ALTER TABLE purchases MODIFY COLUMN total_tax DECIMAL(19,4) DEFAULT 0;
ALTER TABLE purchases MODIFY COLUMN total DECIMAL(19,4) DEFAULT 0;

ALTER TABLE purchase_items MODIFY COLUMN quantity DECIMAL(19,4) DEFAULT 1;
ALTER TABLE purchase_items MODIFY COLUMN cost_price DECIMAL(19,4) DEFAULT 0;
ALTER TABLE purchase_items MODIFY COLUMN subtotal DECIMAL(19,4) DEFAULT 0;

ALTER TABLE sales MODIFY COLUMN subtotal DECIMAL(19,4) DEFAULT 0;
ALTER TABLE sales MODIFY COLUMN total_discount DECIMAL(19,4) DEFAULT 0;
ALTER TABLE sales MODIFY COLUMN total_tax DECIMAL(19,4) DEFAULT 0;
ALTER TABLE sales MODIFY COLUMN total_ice DECIMAL(19,4) DEFAULT 0;
ALTER TABLE sales MODIFY COLUMN total DECIMAL(19,4) DEFAULT 0;
ALTER TABLE sales MODIFY COLUMN exchange_rate DECIMAL(19,8) DEFAULT 1;

ALTER TABLE sale_items MODIFY COLUMN qty DECIMAL(19,4) DEFAULT 1;
ALTER TABLE sale_items MODIFY COLUMN unit_price DECIMAL(19,4) DEFAULT 0;
ALTER TABLE sale_items MODIFY COLUMN discount DECIMAL(19,4) DEFAULT 0;
ALTER TABLE sale_items MODIFY COLUMN ice_rate DECIMAL(9,4) DEFAULT 0;
ALTER TABLE sale_items MODIFY COLUMN tax_rate DECIMAL(9,4) DEFAULT 0;
ALTER TABLE sale_items MODIFY COLUMN line_base DECIMAL(19,4) DEFAULT 0;
ALTER TABLE sale_items MODIFY COLUMN line_discount DECIMAL(19,4) DEFAULT 0;
ALTER TABLE sale_items MODIFY COLUMN line_ice DECIMAL(19,4) DEFAULT 0;
ALTER TABLE sale_items MODIFY COLUMN line_tax DECIMAL(19,4) DEFAULT 0;
ALTER TABLE sale_items MODIFY COLUMN line_total DECIMAL(19,4) DEFAULT 0;

ALTER TABLE payments MODIFY COLUMN amount DECIMAL(19,4);

ALTER TABLE expenses MODIFY COLUMN amount DECIMAL(19,4) DEFAULT 0;

ALTER TABLE production_orders MODIFY COLUMN quantity DECIMAL(19,4);

ALTER TABLE transfers MODIFY COLUMN /* no direct double columns */ id BIGINT;

ALTER TABLE transfer_items MODIFY COLUMN quantity DECIMAL(19,4) DEFAULT 0;
ALTER TABLE transfer_items MODIFY COLUMN quantity_received DECIMAL(19,4) DEFAULT 0;

-- End V17
